### ISSUE TITLE
UX changes to the combine PDF tool

### ISSUE THREAD

**Issue by Fahme** [human-tools/toolbox-web#10]
As a user i would love to be able to have a few UX changes into combine pdf in order to make working with the tool easier : 

- When combining pdfs i want to be able to delete a certain page from the list
- I want to be able to see a full view of a pdf page when click on a thumbnail
- Have a confirmation dialog asking to either append a new uploaded documents into a current working list or create a new list with the uploaded document

**Comment by mkhatib** [comment]
This was fixed!
