### ISSUE TITLE
[CreatePhotosSlideshow] Add ability to change background style and color (solid color instead of blurred duplicate photo)

### ISSUE THREAD

**Issue by mkhatib** [human-tools/toolbox-web#19]

**Comment by mkhatib** [comment]
Yes! These are all great suggestions! Feel free to send PRs for separate ones. 

The most difficult part of this is figuring out the ffmpeg commands to translate all of this to. But I've found trial and error while reading examples people post works well.

**Comment by bnchi** [comment]
Alright i'll give it a shot with the solid color background too @mkhatib
