### ISSUE TITLE
[QuickSignPDF] Only burn paths to PDF after the user click download (not next/prev)

### ISSUE THREAD

**Issue by mkhatib** [human-tools/toolbox-web#20]

**Comment by bnchi** [comment]
What do you think to store the whole svg properties with a references to the pages they belong to in and indexed db and the re-render every-time the user lands on the page ?

This will allow to change colors, thickness and other attributes of the signature easily.

https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API
