### ISSUE TITLE
[QuickSignPDF] Add Hotkeys for deleting selected (Delete/Backspace) and selecting all (Cmd/Ctrl+A) or deselecting all (Cmd/Ctrl+D) annotations

### ISSUE THREAD

**Issue by mkhatib** [human-tools/toolbox-web#86]
We could use `react-hotkeys-hook` Library. 
https://www.npmjs.com/package/react-hotkeys-hook

**Comment by bnchi** [comment]
I added these to the meme tool in this pr #89 let me know what do you think
