### ISSUE TITLE
A tool to turn hand written essays into digital text in the browser

### ISSUE THREAD

**Issue by bnchi** [human-tools/toolbox-web#94]
A-lot of teaching softwares require students to upload their own work to a platform using some sheet of paper. However some students might love to be able to convert these hand-written text into digital format in order to make the text more rich with videos and then export it into PDF, markdown etc .. 

So building a tool that allow for this in the browser without using servers solution like AWS, GCP for OCR would be great. 

A library to use for helping to build a model and classify hand writings would be :
https://ml5js.org -> Building a CNN tool that can take images and classify the text to a great degree

Maybe a more general pre-trained model would be : 
https://tesseract.projectnaptha.com

But I would like to build and train the model using ml5.js first without using tesseract to see how far I can go with English text.

A nice to have feature also would be to convert a hand-written math formulas into Latex

**Comment by bnchi** [comment]
@mkhatib do you believe it's feasible and useful ?

**Comment by bnchi** [comment]
I tested it it turned out to be really slow

**Comment by mkhatib** [comment]
Did you use a tensorflow pretrained model or something else?

**Comment by bnchi** [comment]
pre-trained model. The results were not that good and slow for me, not sure if I was doing something wrong.
