### ISSUE TITLE
[MergePDF] Merging PDFs with forms seem to remove the original Forms in the PDFs

### ISSUE THREAD

**Issue by mkhatib** [human-tools/toolbox-web#95]
The forms should stay intact and interactive. I think this is has to do with how we're creating and saving the new PDF but I am not entirely sure.

**Comment by bnchi** [comment]
[sample_pdf.pdf](https://github.com/human-tools/toolbox-web/files/10368237/sample_pdf.pdf)

I tested with this it seems to be working fine

**Comment by mkhatib** [comment]
hmm You're right. I think I was using a flattened form without noticing. Thanks for testing it out!
